#include "fit_example.h"

static const char *fitFileTbl[] = {
        [FIT_FILE_DEVICE] "DEVICE",
        [FIT_FILE_SETTINGS] "SETTINGS",
        [FIT_FILE_SPORT] "SPORT",
        [FIT_FILE_ACTIVITY] "ACTIVITY",
        [FIT_FILE_WORKOUT] "WORKOUT",
        [FIT_FILE_COURSE] "COURSE",
        [FIT_FILE_SCHEDULES] "SCHEDULES",
        [FIT_FILE_WEIGHT] "WEIGHT",
        [FIT_FILE_TOTALS] "TOTALS",
        [FIT_FILE_GOALS] "GOALS",
        [FIT_FILE_BLOOD_PRESSURE] "BLOOD_PRESSURE",
        [FIT_FILE_MONITORING_A] "MONITORING_A",
        [FIT_FILE_ACTIVITY_SUMMARY] "ACTIVITY_SUMMARY",
        [FIT_FILE_MONITORING_DAILY] "MONITORING_DAILY",
        [FIT_FILE_MONITORING_B] "MONITORING_B",
        [FIT_FILE_SEGMENT] "SEGMENT",
        [FIT_FILE_SEGMENT_LIST] "SEGMENT_LIST",
        [FIT_FILE_EXD_CONFIGURATION] "EXD_CONFIGURATION",
        [FIT_FILE_MFG_RANGE_MIN] "MFG_RANGE_MIN",
        [FIT_FILE_MFG_RANGE_MAX] "MFG_RANGE_MAX",
};

const char *fitFile(FIT_FILE type)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (type != FIT_FILE_INVALID) {
        str = fitFileTbl[type];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", type);
    }

    return fmtBuf;
}

static const char *fitMesgNumTbl[] = {
        [FIT_MESG_NUM_FILE_ID] "FILE_ID",
        [FIT_MESG_NUM_CAPABILITIES] "CAPABILITIES",
        [FIT_MESG_NUM_DEVICE_SETTINGS] "DEVICE_SETTINGS",
        [FIT_MESG_NUM_USER_PROFILE] "USER_PROFILE",
        [FIT_MESG_NUM_HRM_PROFILE] "HRM_PROFILE",
        [FIT_MESG_NUM_SDM_PROFILE] "SDM_PROFILE",
        [FIT_MESG_NUM_BIKE_PROFILE] "BIKE_PROFILE",
        [FIT_MESG_NUM_ZONES_TARGET] "ZONES_TARGET",
        [FIT_MESG_NUM_HR_ZONE] "HR_ZONE",
        [FIT_MESG_NUM_POWER_ZONE] "POWER_ZONE",
        [FIT_MESG_NUM_MET_ZONE] "MET_ZONE",
        [FIT_MESG_NUM_SPORT] "SPORT",
        [FIT_MESG_NUM_GOAL] "GOAL",
        [FIT_MESG_NUM_SESSION] "SESSION",
        [FIT_MESG_NUM_LAP] "LAP",
        [FIT_MESG_NUM_RECORD] "RECORD",
        [FIT_MESG_NUM_EVENT] "EVENT",
        [FIT_MESG_NUM_DEVICE_INFO] "DEVICE_INFO",
        [FIT_MESG_NUM_WORKOUT] "WORKOUT",
        [FIT_MESG_NUM_WORKOUT_STEP] "WORKOUT_STEP",
        [FIT_MESG_NUM_SCHEDULE] "SCHEDULE",
        [FIT_MESG_NUM_WEIGHT_SCALE] "WEIGHT_SCALE",
        [FIT_MESG_NUM_COURSE] "COURSE",
        [FIT_MESG_NUM_COURSE_POINT] "COURSE_POINT",
        [FIT_MESG_NUM_TOTALS] "TOTALS",
        [FIT_MESG_NUM_ACTIVITY] "ACTIVITY",
        [FIT_MESG_NUM_SOFTWARE] "SOFTWARE",
        [FIT_MESG_NUM_FILE_CAPABILITIES] "FILE_CAPABILITIES",
        [FIT_MESG_NUM_MESG_CAPABILITIES] "MESG_CAPABILITIES",
        [FIT_MESG_NUM_FIELD_CAPABILITIES] "FIELD_CAPABILITIES",
        [FIT_MESG_NUM_FILE_CREATOR] "FILE_CREATOR",
        [FIT_MESG_NUM_BLOOD_PRESSURE] "BLOOD_PRESSURE",
        [FIT_MESG_NUM_SPEED_ZONE] "SPEED_ZONE",
        [FIT_MESG_NUM_MONITORING] "MONITORING",
        [FIT_MESG_NUM_TRAINING_FILE] "TRAINING_FILE",
        [FIT_MESG_NUM_HRV] "HRV",
        [FIT_MESG_NUM_ANT_RX] "ANT_RX",
        [FIT_MESG_NUM_ANT_TX] "ANT_TX",
        [FIT_MESG_NUM_ANT_CHANNEL_ID] "ANT_CHANNEL_ID",
        [FIT_MESG_NUM_LENGTH] "LENGTH",
        [FIT_MESG_NUM_MONITORING_INFO] "MONITORING_INFO",
        [FIT_MESG_NUM_PAD] "PAD",
        [FIT_MESG_NUM_SLAVE_DEVICE] "SLAVE_DEVICE",
        [FIT_MESG_NUM_CONNECTIVITY] "CONNECTIVITY",
        [FIT_MESG_NUM_WEATHER_CONDITIONS] "WEATHER_CONDITIONS",
        [FIT_MESG_NUM_WEATHER_ALERT] "WEATHER_ALERT",
        [FIT_MESG_NUM_CADENCE_ZONE] "CADENCE_ZONE",
        [FIT_MESG_NUM_HR] "HR",
        [FIT_MESG_NUM_SEGMENT_LAP] "SEGMENT_LAP",
        [FIT_MESG_NUM_MEMO_GLOB] "MEMO_GLOB",
        [FIT_MESG_NUM_SEGMENT_ID] "SEGMENT_ID",
        [FIT_MESG_NUM_SEGMENT_LEADERBOARD_ENTRY] "SEGMENT_LEADERBOARD_ENTRY",
        [FIT_MESG_NUM_SEGMENT_POINT] "SEGMENT_POINT",
        [FIT_MESG_NUM_SEGMENT_FILE] "SEGMENT_FILE",
        [FIT_MESG_NUM_WORKOUT_SESSION] "WORKOUT_SESSION",
        [FIT_MESG_NUM_WATCHFACE_SETTINGS] "WATCHFACE_SETTINGS",
        [FIT_MESG_NUM_GPS_METADATA] "GPS_METADATA",
        [FIT_MESG_NUM_CAMERA_EVENT] "CAMERA_EVENT",
        [FIT_MESG_NUM_TIMESTAMP_CORRELATION] "TIMESTAMP_CORRELATION",
        [FIT_MESG_NUM_GYROSCOPE_DATA] "GYROSCOPE_DATA",
        [FIT_MESG_NUM_ACCELEROMETER_DATA] "ACCELEROMETER_DATA",
        [FIT_MESG_NUM_THREE_D_SENSOR_CALIBRATION] "THREE_D_SENSOR_CALIBRATION",
        [FIT_MESG_NUM_VIDEO_FRAME] "VIDEO_FRAME",
        [FIT_MESG_NUM_OBDII_DATA] "OBDII_DATA",
        [FIT_MESG_NUM_NMEA_SENTENCE] "NMEA_SENTENCE",
        [FIT_MESG_NUM_AVIATION_ATTITUDE] "AVIATION_ATTITUDE",
        [FIT_MESG_NUM_VIDEO] "VIDEO",
        [FIT_MESG_NUM_VIDEO_TITLE] "VIDEO_TITLE",
        [FIT_MESG_NUM_VIDEO_DESCRIPTION] "VIDEO_DESCRIPTION",
        [FIT_MESG_NUM_VIDEO_CLIP] "VIDEO_CLIP",
        [FIT_MESG_NUM_OHR_SETTINGS] "OHR_SETTINGS",
        [FIT_MESG_NUM_EXD_SCREEN_CONFIGURATION] "EXD_SCREEN_CONFIGURATION",
        [FIT_MESG_NUM_EXD_DATA_FIELD_CONFIGURATION] "EXD_DATA_FIELD_CONFIGURATION",
        [FIT_MESG_NUM_EXD_DATA_CONCEPT_CONFIGURATION] "EXD_DATA_CONCEPT_CONFIGURATION",
        [FIT_MESG_NUM_FIELD_DESCRIPTION] "FIELD_DESCRIPTION",
        [FIT_MESG_NUM_DEVELOPER_DATA_ID] "DEVELOPER_DATA_ID",
        [FIT_MESG_NUM_MAGNETOMETER_DATA] "MAGNETOMETER_DATA",
        [FIT_MESG_NUM_BAROMETER_DATA] "BAROMETER_DATA",
        [FIT_MESG_NUM_ONE_D_SENSOR_CALIBRATION] "ONE_D_SENSOR_CALIBRATION",
        [FIT_MESG_NUM_TIME_IN_ZONE] "TIME_IN_ZONE",
        [FIT_MESG_NUM_SET] "SET",
        [FIT_MESG_NUM_STRESS_LEVEL] "STRESS_LEVEL",
        [FIT_MESG_NUM_DIVE_SETTINGS] "DIVE_SETTINGS",
        [FIT_MESG_NUM_DIVE_GAS] "DIVE_GAS",
        [FIT_MESG_NUM_DIVE_ALARM] "DIVE_ALARM",
        [FIT_MESG_NUM_EXERCISE_TITLE] "EXERCISE_TITLE",
        [FIT_MESG_NUM_DIVE_SUMMARY] "DIVE_SUMMARY",
        [FIT_MESG_NUM_JUMP] "JUMP",
        [FIT_MESG_NUM_SPLIT] "SPLIT",
        [FIT_MESG_NUM_CLIMB_PRO] "CLIMB_PRO",
        [FIT_MESG_NUM_TANK_UPDATE] "TANK_UPDATE",
        [FIT_MESG_NUM_TANK_SUMMARY] "TANK_SUMMARY",
        [FIT_MESG_NUM_DEVICE_AUX_BATTERY_INFO] "DEVICE_AUX_BATTERY_INFO",
        [FIT_MESG_NUM_DIVE_APNEA_ALARM] "DIVE_APNEA_ALARM",
};

const char *fitMesgNum(FIT_MESG_NUM mesg)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (mesg != FIT_MESG_NUM_INVALID) {
        // Special case
        if ((mesg >= FIT_MESG_NUM_MFG_RANGE_MIN) && (mesg <= FIT_MESG_NUM_MFG_RANGE_MAX)) {
            return "MFG_RANGE";
        }
        str = fitMesgNumTbl[mesg];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", mesg);
    }

    return fmtBuf;
}

static const char *fitEventTbl[] = {
        [FIT_EVENT_TIMER] "TIMER",
        [FIT_EVENT_WORKOUT] "WORKOUT",
        [FIT_EVENT_WORKOUT_STEP] "WORKOUT_STEP",
        [FIT_EVENT_POWER_DOWN] "POWER_DOWN",
        [FIT_EVENT_POWER_UP] "POWER_UP",
        [FIT_EVENT_OFF_COURSE] "OFF_COURSE",
        [FIT_EVENT_SESSION] "SESSION",
        [FIT_EVENT_LAP] "LAP",
        [FIT_EVENT_COURSE_POINT] "COURSE_POINT",
        [FIT_EVENT_BATTERY] "BATTERY",
        [FIT_EVENT_VIRTUAL_PARTNER_PACE] "VIRTUAL_PARTNER_PACE",
        [FIT_EVENT_HR_HIGH_ALERT] "HR_HIGH_ALERT",
        [FIT_EVENT_HR_LOW_ALERT] "HR_LOW_ALERT",
        [FIT_EVENT_SPEED_HIGH_ALERT] "SPEED_HIGH_ALERT",
        [FIT_EVENT_SPEED_LOW_ALERT] "SPEED_LOW_ALERT",
        [FIT_EVENT_CAD_HIGH_ALERT] "CAD_HIGH_ALERT",
        [FIT_EVENT_CAD_LOW_ALERT] "CAD_LOW_ALERT",
        [FIT_EVENT_POWER_HIGH_ALERT] "POWER_HIGH_ALERT",
        [FIT_EVENT_POWER_LOW_ALERT] "POWER_LOW_ALERT",
        [FIT_EVENT_RECOVERY_HR] "RECOVERY_HR",
        [FIT_EVENT_BATTERY_LOW] "BATTERY_LOW",
        [FIT_EVENT_TIME_DURATION_ALERT] "TIME_DURATION_ALERT",
        [FIT_EVENT_DISTANCE_DURATION_ALERT] "DISTANCE_DURATION_ALERT",
        [FIT_EVENT_CALORIE_DURATION_ALERT] "CALORIE_DURATION_ALERT",
        [FIT_EVENT_ACTIVITY] "ACTIVITY",
        [FIT_EVENT_FITNESS_EQUIPMENT] "FITNESS_EQUIPMENT",
        [FIT_EVENT_LENGTH] "LENGTH",
        [FIT_EVENT_USER_MARKER] "USER_MARKER",
        [FIT_EVENT_SPORT_POINT] "SPORT_POINT",
        [FIT_EVENT_CALIBRATION] "CALIBRATION",
        [FIT_EVENT_FRONT_GEAR_CHANGE] "FRONT_GEAR_CHANGE",
        [FIT_EVENT_REAR_GEAR_CHANGE] "REAR_GEAR_CHANGE",
        [FIT_EVENT_RIDER_POSITION_CHANGE] "RIDER_POSITION_CHANGE",
        [FIT_EVENT_ELEV_HIGH_ALERT] "ELEV_HIGH_ALERT",
        [FIT_EVENT_ELEV_LOW_ALERT] "ELEV_LOW_ALERT",
        [FIT_EVENT_COMM_TIMEOUT] "COMM_TIMEOUT",
        [FIT_EVENT_DIVE_ALERT] "DIVE_ALERT",
        [FIT_EVENT_DIVE_GAS_SWITCHED] "DIVE_GAS_SWITCHED",
        [FIT_EVENT_TANK_PRESSURE_RESERVE] "TANK_PRESSURE_RESERVE",
        [FIT_EVENT_TANK_PRESSURE_CRITICAL] "TANK_PRESSURE_CRITICAL",
        [FIT_EVENT_TANK_LOST] "TANK_LOST",
        [FIT_EVENT_RADAR_THREAT_ALERT] "RADAR_THREAT_ALERT",
        [FIT_EVENT_TANK_BATTERY_LOW] "TANK_BATTERY_LOW",
        [FIT_EVENT_TANK_POD_CONNECTED] "TANK_POD_CONNECTED",
        [FIT_EVENT_TANK_POD_DISCONNECTED] "TANK_POD_DISCONNECTED",
};

const char *fitEvent(FIT_EVENT event)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (event != FIT_EVENT_INVALID) {
        str = fitEventTbl[event];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", event);
    }

    return fmtBuf;
}

static const char *fitEventTypeTbl[] = {
        [FIT_EVENT_TYPE_START] "TYPE_START",
        [FIT_EVENT_TYPE_STOP] "TYPE_STOP",
        [FIT_EVENT_TYPE_CONSECUTIVE_DEPRECIATED] "TYPE_CONSECUTIVE_DEPRECIATED",
        [FIT_EVENT_TYPE_MARKER] "TYPE_MARKER",
        [FIT_EVENT_TYPE_STOP_ALL] "TYPE_STOP_ALL",
        [FIT_EVENT_TYPE_BEGIN_DEPRECIATED] "TYPE_BEGIN_DEPRECIATED",
        [FIT_EVENT_TYPE_END_DEPRECIATED] "TYPE_END_DEPRECIATED",
        [FIT_EVENT_TYPE_END_ALL_DEPRECIATED] "TYPE_END_ALL_DEPRECIATED",
        [FIT_EVENT_TYPE_STOP_DISABLE] "TYPE_STOP_DISABLE",
        [FIT_EVENT_TYPE_STOP_DISABLE_ALL] "TYPE_STOP_DISABLE_ALL",
};

const char *fitEventType(FIT_EVENT_TYPE type)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (type != FIT_EVENT_TYPE_INVALID) {
        str = fitEventTypeTbl[type];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", type);
    }

    return fmtBuf;
}

static const char *fitManufacturerTbl[] = {
        [FIT_MANUFACTURER_GARMIN] "GARMIN",
        [FIT_MANUFACTURER_GARMIN_FR405_ANTFS] "GARMIN_FR405_ANTFS",
        [FIT_MANUFACTURER_ZEPHYR] "ZEPHYR",
        [FIT_MANUFACTURER_DAYTON] "DAYTON",
        [FIT_MANUFACTURER_IDT] "IDT",
        [FIT_MANUFACTURER_SRM] "SRM",
        [FIT_MANUFACTURER_QUARQ] "QUARQ",
        [FIT_MANUFACTURER_IBIKE] "IBIKE",
        [FIT_MANUFACTURER_SARIS] "SARIS",
        [FIT_MANUFACTURER_SPARK_HK] "SPARK_HK",
        [FIT_MANUFACTURER_TANITA] "TANITA",
        [FIT_MANUFACTURER_ECHOWELL] "ECHOWELL",
        [FIT_MANUFACTURER_DYNASTREAM_OEM] "DYNASTREAM_OEM",
        [FIT_MANUFACTURER_NAUTILUS] "NAUTILUS",
        [FIT_MANUFACTURER_DYNASTREAM] "DYNASTREAM",
        [FIT_MANUFACTURER_TIMEX] "TIMEX",
        [FIT_MANUFACTURER_METRIGEAR] "METRIGEAR",
        [FIT_MANUFACTURER_XELIC] "XELIC",
        [FIT_MANUFACTURER_BEURER] "BEURER",
        [FIT_MANUFACTURER_CARDIOSPORT] "CARDIOSPORT",
        [FIT_MANUFACTURER_A_AND_D] "A_AND_D",
        [FIT_MANUFACTURER_HMM] "HMM",
        [FIT_MANUFACTURER_SUUNTO] "SUUNTO",
        [FIT_MANUFACTURER_THITA_ELEKTRONIK] "THITA_ELEKTRONIK",
        [FIT_MANUFACTURER_GPULSE] "GPULSE",
        [FIT_MANUFACTURER_CLEAN_MOBILE] "CLEAN_MOBILE",
        [FIT_MANUFACTURER_PEDAL_BRAIN] "PEDAL_BRAIN",
        [FIT_MANUFACTURER_PEAKSWARE] "PEAKSWARE",
        [FIT_MANUFACTURER_SAXONAR] "SAXONAR",
        [FIT_MANUFACTURER_LEMOND_FITNESS] "LEMOND_FITNESS",
        [FIT_MANUFACTURER_DEXCOM] "DEXCOM",
        [FIT_MANUFACTURER_WAHOO_FITNESS] "WAHOO_FITNESS",
        [FIT_MANUFACTURER_OCTANE_FITNESS] "OCTANE_FITNESS",
        [FIT_MANUFACTURER_ARCHINOETICS] "ARCHINOETICS",
        [FIT_MANUFACTURER_THE_HURT_BOX] "THE_HURT_BOX",
        [FIT_MANUFACTURER_CITIZEN_SYSTEMS] "CITIZEN_SYSTEMS",
        [FIT_MANUFACTURER_MAGELLAN] "MAGELLAN",
        [FIT_MANUFACTURER_OSYNCE] "OSYNCE",
        [FIT_MANUFACTURER_HOLUX] "HOLUX",
        [FIT_MANUFACTURER_CONCEPT2] "CONCEPT2",
        [FIT_MANUFACTURER_SHIMANO] "SHIMANO",
        [FIT_MANUFACTURER_ONE_GIANT_LEAP] "ONE_GIANT_LEAP",
        [FIT_MANUFACTURER_ACE_SENSOR] "ACE_SENSOR",
        [FIT_MANUFACTURER_BRIM_BROTHERS] "BRIM_BROTHERS",
        [FIT_MANUFACTURER_XPLOVA] "XPLOVA",
        [FIT_MANUFACTURER_PERCEPTION_DIGITAL] "PERCEPTION_DIGITAL",
        [FIT_MANUFACTURER_BF1SYSTEMS] "BF1SYSTEMS",
        [FIT_MANUFACTURER_PIONEER] "PIONEER",
        [FIT_MANUFACTURER_SPANTEC] "SPANTEC",
        [FIT_MANUFACTURER_METALOGICS] "METALOGICS",
        [FIT_MANUFACTURER_4IIIIS] "4IIIIS",
        [FIT_MANUFACTURER_SEIKO_EPSON] "SEIKO_EPSON",
        [FIT_MANUFACTURER_SEIKO_EPSON_OEM] "SEIKO_EPSON_OEM",
        [FIT_MANUFACTURER_IFOR_POWELL] "IFOR_POWELL",
        [FIT_MANUFACTURER_MAXWELL_GUIDER] "MAXWELL_GUIDER",
        [FIT_MANUFACTURER_STAR_TRAC] "STAR_TRAC",
        [FIT_MANUFACTURER_BREAKAWAY] "BREAKAWAY",
        [FIT_MANUFACTURER_ALATECH_TECHNOLOGY_LTD] "ALATECH_TECHNOLOGY_LTD",
        [FIT_MANUFACTURER_MIO_TECHNOLOGY_EUROPE] "MIO_TECHNOLOGY_EUROPE",
        [FIT_MANUFACTURER_ROTOR] "ROTOR",
        [FIT_MANUFACTURER_GEONAUTE] "GEONAUTE",
        [FIT_MANUFACTURER_ID_BIKE] "ID_BIKE",
        [FIT_MANUFACTURER_SPECIALIZED] "SPECIALIZED",
        [FIT_MANUFACTURER_WTEK] "WTEK",
        [FIT_MANUFACTURER_PHYSICAL_ENTERPRISES] "PHYSICAL_ENTERPRISES",
        [FIT_MANUFACTURER_NORTH_POLE_ENGINEERING] "NORTH_POLE_ENGINEERING",
        [FIT_MANUFACTURER_BKOOL] "BKOOL",
        [FIT_MANUFACTURER_CATEYE] "CATEYE",
        [FIT_MANUFACTURER_STAGES_CYCLING] "STAGES_CYCLING",
        [FIT_MANUFACTURER_SIGMASPORT] "SIGMASPORT",
        [FIT_MANUFACTURER_TOMTOM] "TOMTOM",
        [FIT_MANUFACTURER_PERIPEDAL] "PERIPEDAL",
        [FIT_MANUFACTURER_WATTBIKE] "WATTBIKE",
        [FIT_MANUFACTURER_MOXY] "MOXY",
        [FIT_MANUFACTURER_CICLOSPORT] "CICLOSPORT",
        [FIT_MANUFACTURER_POWERBAHN] "POWERBAHN",
        [FIT_MANUFACTURER_ACORN_PROJECTS_APS] "ACORN_PROJECTS_APS",
        [FIT_MANUFACTURER_LIFEBEAM] "LIFEBEAM",
        [FIT_MANUFACTURER_BONTRAGER] "BONTRAGER",
        [FIT_MANUFACTURER_WELLGO] "WELLGO",
        [FIT_MANUFACTURER_SCOSCHE] "SCOSCHE",
        [FIT_MANUFACTURER_MAGURA] "MAGURA",
        [FIT_MANUFACTURER_WOODWAY] "WOODWAY",
        [FIT_MANUFACTURER_ELITE] "ELITE",
        [FIT_MANUFACTURER_NIELSEN_KELLERMAN] "NIELSEN_KELLERMAN",
        [FIT_MANUFACTURER_DK_CITY] "DK_CITY",
        [FIT_MANUFACTURER_TACX] "TACX",
        [FIT_MANUFACTURER_DIRECTION_TECHNOLOGY] "DIRECTION_TECHNOLOGY",
        [FIT_MANUFACTURER_MAGTONIC] "MAGTONIC",
        [FIT_MANUFACTURER_1PARTCARBON] "1PARTCARBON",
        [FIT_MANUFACTURER_INSIDE_RIDE_TECHNOLOGIES] "INSIDE_RIDE_TECHNOLOGIES",
        [FIT_MANUFACTURER_SOUND_OF_MOTION] "SOUND_OF_MOTION",
        [FIT_MANUFACTURER_STRYD] "STRYD",
        [FIT_MANUFACTURER_ICG] "ICG",
        [FIT_MANUFACTURER_MIPULSE] "MIPULSE",
        [FIT_MANUFACTURER_BSX_ATHLETICS] "BSX_ATHLETICS",
        [FIT_MANUFACTURER_LOOK] "LOOK",
        [FIT_MANUFACTURER_CAMPAGNOLO_SRL] "CAMPAGNOLO_SRL",
        [FIT_MANUFACTURER_BODY_BIKE_SMART] "BODY_BIKE_SMART",
        [FIT_MANUFACTURER_PRAXISWORKS] "PRAXISWORKS",
        [FIT_MANUFACTURER_LIMITS_TECHNOLOGY] "LIMITS_TECHNOLOGY",
        [FIT_MANUFACTURER_TOPACTION_TECHNOLOGY] "TOPACTION_TECHNOLOGY",
        [FIT_MANUFACTURER_COSINUSS] "COSINUSS",
        [FIT_MANUFACTURER_FITCARE] "FITCARE",
        [FIT_MANUFACTURER_MAGENE] "MAGENE",
        [FIT_MANUFACTURER_GIANT_MANUFACTURING_CO] "GIANT_MANUFACTURING_CO",
        [FIT_MANUFACTURER_TIGRASPORT] "TIGRASPORT",
        [FIT_MANUFACTURER_SALUTRON] "SALUTRON",
        [FIT_MANUFACTURER_TECHNOGYM] "TECHNOGYM",
        [FIT_MANUFACTURER_BRYTON_SENSORS] "BRYTON_SENSORS",
        [FIT_MANUFACTURER_LATITUDE_LIMITED] "LATITUDE_LIMITED",
        [FIT_MANUFACTURER_SOARING_TECHNOLOGY] "SOARING_TECHNOLOGY",
        [FIT_MANUFACTURER_IGPSPORT] "IGPSPORT",
        [FIT_MANUFACTURER_THINKRIDER] "THINKRIDER",
        [FIT_MANUFACTURER_GOPHER_SPORT] "GOPHER_SPORT",
        [FIT_MANUFACTURER_WATERROWER] "WATERROWER",
        [FIT_MANUFACTURER_ORANGETHEORY] "ORANGETHEORY",
        [FIT_MANUFACTURER_INPEAK] "INPEAK",
        [FIT_MANUFACTURER_KINETIC] "KINETIC",
        [FIT_MANUFACTURER_JOHNSON_HEALTH_TECH] "JOHNSON_HEALTH_TECH",
        [FIT_MANUFACTURER_POLAR_ELECTRO] "POLAR_ELECTRO",
        [FIT_MANUFACTURER_SEESENSE] "SEESENSE",
        [FIT_MANUFACTURER_NCI_TECHNOLOGY] "NCI_TECHNOLOGY",
        [FIT_MANUFACTURER_IQSQUARE] "IQSQUARE",
        [FIT_MANUFACTURER_LEOMO] "LEOMO",
        [FIT_MANUFACTURER_IFIT_COM] "IFIT_COM",
        [FIT_MANUFACTURER_COROS_BYTE] "COROS_BYTE",
        [FIT_MANUFACTURER_VERSA_DESIGN] "VERSA_DESIGN",
        [FIT_MANUFACTURER_CHILEAF] "CHILEAF",
        [FIT_MANUFACTURER_CYCPLUS] "CYCPLUS",
        [FIT_MANUFACTURER_GRAVAA_BYTE] "GRAVAA_BYTE",
        [FIT_MANUFACTURER_SIGEYI] "SIGEYI",
        [FIT_MANUFACTURER_COOSPO] "COOSPO",
        [FIT_MANUFACTURER_GEOID] "GEOID",
        [FIT_MANUFACTURER_BOSCH] "BOSCH",
        [FIT_MANUFACTURER_KYTO] "KYTO",
        [FIT_MANUFACTURER_KINETIC_SPORTS] "KINETIC_SPORTS",
        [FIT_MANUFACTURER_DECATHLON_BYTE] "DECATHLON_BYTE",
        [FIT_MANUFACTURER_TQ_SYSTEMS] "TQ_SYSTEMS",
        [FIT_MANUFACTURER_TAG_HEUER] "TAG_HEUER",
        [FIT_MANUFACTURER_KEISER_FITNESS] "KEISER_FITNESS",
        [FIT_MANUFACTURER_ZWIFT_BYTE] "ZWIFT_BYTE",
        [FIT_MANUFACTURER_PORSCHE_EP] "PORSCHE_EP",
        [FIT_MANUFACTURER_DEVELOPMENT] "DEVELOPMENT",
        [FIT_MANUFACTURER_HEALTHANDLIFE] "HEALTHANDLIFE",
        [FIT_MANUFACTURER_LEZYNE] "LEZYNE",
        [FIT_MANUFACTURER_SCRIBE_LABS] "SCRIBE_LABS",
        [FIT_MANUFACTURER_ZWIFT] "ZWIFT",
        [FIT_MANUFACTURER_WATTEAM] "WATTEAM",
        [FIT_MANUFACTURER_RECON] "RECON",
        [FIT_MANUFACTURER_FAVERO_ELECTRONICS] "FAVERO_ELECTRONICS",
        [FIT_MANUFACTURER_DYNOVELO] "DYNOVELO",
        [FIT_MANUFACTURER_STRAVA] "STRAVA",
        [FIT_MANUFACTURER_PRECOR] "PRECOR",
        [FIT_MANUFACTURER_BRYTON] "BRYTON",
        [FIT_MANUFACTURER_SRAM] "SRAM",
        [FIT_MANUFACTURER_NAVMAN] "NAVMAN",
        [FIT_MANUFACTURER_COBI] "COBI",
        [FIT_MANUFACTURER_SPIVI] "SPIVI",
        [FIT_MANUFACTURER_MIO_MAGELLAN] "MIO_MAGELLAN",
        [FIT_MANUFACTURER_EVESPORTS] "EVESPORTS",
        [FIT_MANUFACTURER_SENSITIVUS_GAUGE] "SENSITIVUS_GAUGE",
        [FIT_MANUFACTURER_PODOON] "PODOON",
        [FIT_MANUFACTURER_LIFE_TIME_FITNESS] "LIFE_TIME_FITNESS",
        [FIT_MANUFACTURER_FALCO_E_MOTORS] "FALCO_E_MOTORS",
        [FIT_MANUFACTURER_MINOURA] "MINOURA",
        [FIT_MANUFACTURER_CYCLIQ] "CYCLIQ",
        [FIT_MANUFACTURER_LUXOTTICA] "LUXOTTICA",
        [FIT_MANUFACTURER_TRAINER_ROAD] "TRAINER_ROAD",
        [FIT_MANUFACTURER_THE_SUFFERFEST] "THE_SUFFERFEST",
        [FIT_MANUFACTURER_FULLSPEEDAHEAD] "FULLSPEEDAHEAD",
        [FIT_MANUFACTURER_VIRTUALTRAINING] "VIRTUALTRAINING",
        [FIT_MANUFACTURER_FEEDBACKSPORTS] "FEEDBACKSPORTS",
        [FIT_MANUFACTURER_OMATA] "OMATA",
        [FIT_MANUFACTURER_VDO] "VDO",
        [FIT_MANUFACTURER_MAGNETICDAYS] "MAGNETICDAYS",
        [FIT_MANUFACTURER_HAMMERHEAD] "HAMMERHEAD",
        [FIT_MANUFACTURER_KINETIC_BY_KURT] "KINETIC_BY_KURT",
        [FIT_MANUFACTURER_SHAPELOG] "SHAPELOG",
        [FIT_MANUFACTURER_DABUZIDUO] "DABUZIDUO",
        [FIT_MANUFACTURER_JETBLACK] "JETBLACK",
        [FIT_MANUFACTURER_COROS] "COROS",
        [FIT_MANUFACTURER_VIRTUGO] "VIRTUGO",
        [FIT_MANUFACTURER_VELOSENSE] "VELOSENSE",
        [FIT_MANUFACTURER_CYCLIGENTINC] "CYCLIGENTINC",
        [FIT_MANUFACTURER_TRAILFORKS] "TRAILFORKS",
        [FIT_MANUFACTURER_MAHLE_EBIKEMOTION] "MAHLE_EBIKEMOTION",
        [FIT_MANUFACTURER_NURVV] "NURVV",
        [FIT_MANUFACTURER_MICROPROGRAM] "MICROPROGRAM",
        [FIT_MANUFACTURER_ZONE5CLOUD] "ZONE5CLOUD",
        [FIT_MANUFACTURER_GREENTEG] "GREENTEG",
        [FIT_MANUFACTURER_YAMAHA_MOTORS] "YAMAHA_MOTORS",
        [FIT_MANUFACTURER_WHOOP] "WHOOP",
        [FIT_MANUFACTURER_GRAVAA] "GRAVAA",
        [FIT_MANUFACTURER_ONELAP] "ONELAP",
        [FIT_MANUFACTURER_MONARK_EXERCISE] "MONARK_EXERCISE",
        [FIT_MANUFACTURER_FORM] "FORM",
        [FIT_MANUFACTURER_DECATHLON] "DECATHLON",
        [FIT_MANUFACTURER_SYNCROS] "SYNCROS",
        [FIT_MANUFACTURER_HEATUP] "HEATUP",
        [FIT_MANUFACTURER_CANNONDALE] "CANNONDALE",
        [FIT_MANUFACTURER_TRUE_FITNESS] "TRUE_FITNESS",
        [FIT_MANUFACTURER_RGT_CYCLING] "RGT_CYCLING",
        [FIT_MANUFACTURER_VASA] "VASA",
        [FIT_MANUFACTURER_RACE_REPUBLIC] "RACE_REPUBLIC",
        [FIT_MANUFACTURER_FAZUA] "FAZUA",
        [FIT_MANUFACTURER_OREKA_TRAINING] "OREKA_TRAINING",
        [FIT_MANUFACTURER_LSEC] "LSEC",
        [FIT_MANUFACTURER_LULULEMON_STUDIO] "LULULEMON_STUDIO",
        [FIT_MANUFACTURER_SHANYUE] "SHANYUE",
        [FIT_MANUFACTURER_ACTIGRAPHCORP] "ACTIGRAPHCORP",
};

const char *fitManufacturer(FIT_MANUFACTURER manufacturer)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (manufacturer != FIT_MANUFACTURER_INVALID) {
        str = fitManufacturerTbl[manufacturer];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", manufacturer);
    }

    return fmtBuf;
}

static const char *fitGarminProductTbl[] = {
        [FIT_GARMIN_PRODUCT_HRM1] "HRM1",
        [FIT_GARMIN_PRODUCT_AXH01] "AXH01",
        [FIT_GARMIN_PRODUCT_AXB01] "AXB01",
        [FIT_GARMIN_PRODUCT_AXB02] "AXB02",
        [FIT_GARMIN_PRODUCT_HRM2SS] "HRM2SS",
        [FIT_GARMIN_PRODUCT_DSI_ALF02] "DSI_ALF02",
        [FIT_GARMIN_PRODUCT_HRM3SS] "HRM3SS",
        [FIT_GARMIN_PRODUCT_HRM_RUN_SINGLE_BYTE_PRODUCT_ID] "HRM_RUN_SINGLE_BYTE_PRODUCT_ID",
        [FIT_GARMIN_PRODUCT_BSM] "BSM",
        [FIT_GARMIN_PRODUCT_BCM] "BCM",
        [FIT_GARMIN_PRODUCT_AXS01] "AXS01",
        [FIT_GARMIN_PRODUCT_HRM_TRI_SINGLE_BYTE_PRODUCT_ID] "HRM_TRI_SINGLE_BYTE_PRODUCT_ID",
        [FIT_GARMIN_PRODUCT_HRM4_RUN_SINGLE_BYTE_PRODUCT_ID] "HRM4_RUN_SINGLE_BYTE_PRODUCT_ID",
        [FIT_GARMIN_PRODUCT_FR225_SINGLE_BYTE_PRODUCT_ID] "FR225_SINGLE_BYTE_PRODUCT_ID",
        [FIT_GARMIN_PRODUCT_GEN3_BSM_SINGLE_BYTE_PRODUCT_ID] "GEN3_BSM_SINGLE_BYTE_PRODUCT_ID",
        [FIT_GARMIN_PRODUCT_GEN3_BCM_SINGLE_BYTE_PRODUCT_ID] "GEN3_BCM_SINGLE_BYTE_PRODUCT_ID",
        [FIT_GARMIN_PRODUCT_OHR] "OHR",
        [FIT_GARMIN_PRODUCT_FR301_CHINA] "FR301_CHINA",
        [FIT_GARMIN_PRODUCT_FR301_JAPAN] "FR301_JAPAN",
        [FIT_GARMIN_PRODUCT_FR301_KOREA] "FR301_KOREA",
        [FIT_GARMIN_PRODUCT_FR301_TAIWAN] "FR301_TAIWAN",
        [FIT_GARMIN_PRODUCT_FR405] "FR405",
        [FIT_GARMIN_PRODUCT_FR50] "FR50",
        [FIT_GARMIN_PRODUCT_FR405_JAPAN] "FR405_JAPAN",
        [FIT_GARMIN_PRODUCT_FR60] "FR60",
        [FIT_GARMIN_PRODUCT_DSI_ALF01] "DSI_ALF01",
        [FIT_GARMIN_PRODUCT_FR310XT] "FR310XT",
        [FIT_GARMIN_PRODUCT_EDGE500] "EDGE500",
        [FIT_GARMIN_PRODUCT_FR110] "FR110",
        [FIT_GARMIN_PRODUCT_EDGE800] "EDGE800",
        [FIT_GARMIN_PRODUCT_EDGE500_TAIWAN] "EDGE500_TAIWAN",
        [FIT_GARMIN_PRODUCT_EDGE500_JAPAN] "EDGE500_JAPAN",
        [FIT_GARMIN_PRODUCT_CHIRP] "CHIRP",
        [FIT_GARMIN_PRODUCT_FR110_JAPAN] "FR110_JAPAN",
        [FIT_GARMIN_PRODUCT_EDGE200] "EDGE200",
        [FIT_GARMIN_PRODUCT_FR910XT] "FR910XT",
        [FIT_GARMIN_PRODUCT_EDGE800_TAIWAN] "EDGE800_TAIWAN",
        [FIT_GARMIN_PRODUCT_EDGE800_JAPAN] "EDGE800_JAPAN",
        [FIT_GARMIN_PRODUCT_ALF04] "ALF04",
        [FIT_GARMIN_PRODUCT_FR610] "FR610",
        [FIT_GARMIN_PRODUCT_FR210_JAPAN] "FR210_JAPAN",
        [FIT_GARMIN_PRODUCT_VECTOR_SS] "VECTOR_SS",
        [FIT_GARMIN_PRODUCT_VECTOR_CP] "VECTOR_CP",
        [FIT_GARMIN_PRODUCT_EDGE800_CHINA] "EDGE800_CHINA",
        [FIT_GARMIN_PRODUCT_EDGE500_CHINA] "EDGE500_CHINA",
        [FIT_GARMIN_PRODUCT_APPROACH_G10] "APPROACH_G10",
        [FIT_GARMIN_PRODUCT_FR610_JAPAN] "FR610_JAPAN",
        [FIT_GARMIN_PRODUCT_EDGE500_KOREA] "EDGE500_KOREA",
        [FIT_GARMIN_PRODUCT_FR70] "FR70",
        [FIT_GARMIN_PRODUCT_FR310XT_4T] "FR310XT_4T",
        [FIT_GARMIN_PRODUCT_AMX] "AMX",
        [FIT_GARMIN_PRODUCT_FR10] "FR10",
        [FIT_GARMIN_PRODUCT_EDGE800_KOREA] "EDGE800_KOREA",
        [FIT_GARMIN_PRODUCT_SWIM] "SWIM",
        [FIT_GARMIN_PRODUCT_FR910XT_CHINA] "FR910XT_CHINA",
        [FIT_GARMIN_PRODUCT_FENIX] "FENIX",
        [FIT_GARMIN_PRODUCT_EDGE200_TAIWAN] "EDGE200_TAIWAN",
        [FIT_GARMIN_PRODUCT_EDGE510] "EDGE510",
        [FIT_GARMIN_PRODUCT_EDGE810] "EDGE810",
        [FIT_GARMIN_PRODUCT_TEMPE] "TEMPE",
        [FIT_GARMIN_PRODUCT_FR910XT_JAPAN] "FR910XT_JAPAN",
        [FIT_GARMIN_PRODUCT_FR620] "FR620",
        [FIT_GARMIN_PRODUCT_FR220] "FR220",
        [FIT_GARMIN_PRODUCT_FR910XT_KOREA] "FR910XT_KOREA",
        [FIT_GARMIN_PRODUCT_FR10_JAPAN] "FR10_JAPAN",
        [FIT_GARMIN_PRODUCT_EDGE810_JAPAN] "EDGE810_JAPAN",
        [FIT_GARMIN_PRODUCT_VIRB_ELITE] "VIRB_ELITE",
        [FIT_GARMIN_PRODUCT_EDGE_TOURING] "EDGE_TOURING",
        [FIT_GARMIN_PRODUCT_EDGE510_JAPAN] "EDGE510_JAPAN",
        [FIT_GARMIN_PRODUCT_HRM_TRI] "HRM_TRI",
        [FIT_GARMIN_PRODUCT_HRM_RUN] "HRM_RUN",
        [FIT_GARMIN_PRODUCT_FR920XT] "FR920XT",
        [FIT_GARMIN_PRODUCT_EDGE510_ASIA] "EDGE510_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE810_CHINA] "EDGE810_CHINA",
        [FIT_GARMIN_PRODUCT_EDGE810_TAIWAN] "EDGE810_TAIWAN",
        [FIT_GARMIN_PRODUCT_EDGE1000] "EDGE1000",
        [FIT_GARMIN_PRODUCT_VIVO_FIT] "VIVO_FIT",
        [FIT_GARMIN_PRODUCT_VIRB_REMOTE] "VIRB_REMOTE",
        [FIT_GARMIN_PRODUCT_VIVO_KI] "VIVO_KI",
        [FIT_GARMIN_PRODUCT_FR15] "FR15",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE] "VIVO_ACTIVE",
        [FIT_GARMIN_PRODUCT_EDGE510_KOREA] "EDGE510_KOREA",
        [FIT_GARMIN_PRODUCT_FR620_JAPAN] "FR620_JAPAN",
        [FIT_GARMIN_PRODUCT_FR620_CHINA] "FR620_CHINA",
        [FIT_GARMIN_PRODUCT_FR220_JAPAN] "FR220_JAPAN",
        [FIT_GARMIN_PRODUCT_FR220_CHINA] "FR220_CHINA",
        [FIT_GARMIN_PRODUCT_APPROACH_S6] "APPROACH_S6",
        [FIT_GARMIN_PRODUCT_VIVO_SMART] "VIVO_SMART",
        [FIT_GARMIN_PRODUCT_FENIX2] "FENIX2",
        [FIT_GARMIN_PRODUCT_EPIX] "EPIX",
        [FIT_GARMIN_PRODUCT_FENIX3] "FENIX3",
        [FIT_GARMIN_PRODUCT_EDGE1000_TAIWAN] "EDGE1000_TAIWAN",
        [FIT_GARMIN_PRODUCT_EDGE1000_JAPAN] "EDGE1000_JAPAN",
        [FIT_GARMIN_PRODUCT_FR15_JAPAN] "FR15_JAPAN",
        [FIT_GARMIN_PRODUCT_EDGE520] "EDGE520",
        [FIT_GARMIN_PRODUCT_EDGE1000_CHINA] "EDGE1000_CHINA",
        [FIT_GARMIN_PRODUCT_FR620_RUSSIA] "FR620_RUSSIA",
        [FIT_GARMIN_PRODUCT_FR220_RUSSIA] "FR220_RUSSIA",
        [FIT_GARMIN_PRODUCT_VECTOR_S] "VECTOR_S",
        [FIT_GARMIN_PRODUCT_EDGE1000_KOREA] "EDGE1000_KOREA",
        [FIT_GARMIN_PRODUCT_FR920XT_TAIWAN] "FR920XT_TAIWAN",
        [FIT_GARMIN_PRODUCT_FR920XT_CHINA] "FR920XT_CHINA",
        [FIT_GARMIN_PRODUCT_FR920XT_JAPAN] "FR920XT_JAPAN",
        [FIT_GARMIN_PRODUCT_VIRBX] "VIRBX",
        [FIT_GARMIN_PRODUCT_VIVO_SMART_APAC] "VIVO_SMART_APAC",
        [FIT_GARMIN_PRODUCT_ETREX_TOUCH] "ETREX_TOUCH",
        [FIT_GARMIN_PRODUCT_EDGE25] "EDGE25",
        [FIT_GARMIN_PRODUCT_FR25] "FR25",
        [FIT_GARMIN_PRODUCT_VIVO_FIT2] "VIVO_FIT2",
        [FIT_GARMIN_PRODUCT_FR225] "FR225",
        [FIT_GARMIN_PRODUCT_FR630] "FR630",
        [FIT_GARMIN_PRODUCT_FR230] "FR230",
        [FIT_GARMIN_PRODUCT_FR735XT] "FR735XT",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE_APAC] "VIVO_ACTIVE_APAC",
        [FIT_GARMIN_PRODUCT_VECTOR_2] "VECTOR_2",
        [FIT_GARMIN_PRODUCT_VECTOR_2S] "VECTOR_2S",
        [FIT_GARMIN_PRODUCT_VIRBXE] "VIRBXE",
        [FIT_GARMIN_PRODUCT_FR620_TAIWAN] "FR620_TAIWAN",
        [FIT_GARMIN_PRODUCT_FR220_TAIWAN] "FR220_TAIWAN",
        [FIT_GARMIN_PRODUCT_TRUSWING] "TRUSWING",
        [FIT_GARMIN_PRODUCT_D2AIRVENU] "D2AIRVENU",
        [FIT_GARMIN_PRODUCT_FENIX3_CHINA] "FENIX3_CHINA",
        [FIT_GARMIN_PRODUCT_FENIX3_TWN] "FENIX3_TWN",
        [FIT_GARMIN_PRODUCT_VARIA_HEADLIGHT] "VARIA_HEADLIGHT",
        [FIT_GARMIN_PRODUCT_VARIA_TAILLIGHT_OLD] "VARIA_TAILLIGHT_OLD",
        [FIT_GARMIN_PRODUCT_EDGE_EXPLORE_1000] "EDGE_EXPLORE_1000",
        [FIT_GARMIN_PRODUCT_FR225_ASIA] "FR225_ASIA",
        [FIT_GARMIN_PRODUCT_VARIA_RADAR_TAILLIGHT] "VARIA_RADAR_TAILLIGHT",
        [FIT_GARMIN_PRODUCT_VARIA_RADAR_DISPLAY] "VARIA_RADAR_DISPLAY",
        [FIT_GARMIN_PRODUCT_EDGE20] "EDGE20",
        [FIT_GARMIN_PRODUCT_EDGE520_ASIA] "EDGE520_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE520_JAPAN] "EDGE520_JAPAN",
        [FIT_GARMIN_PRODUCT_D2_BRAVO] "D2_BRAVO",
        [FIT_GARMIN_PRODUCT_APPROACH_S20] "APPROACH_S20",
        [FIT_GARMIN_PRODUCT_VIVO_SMART2] "VIVO_SMART2",
        [FIT_GARMIN_PRODUCT_EDGE1000_THAI] "EDGE1000_THAI",
        [FIT_GARMIN_PRODUCT_VARIA_REMOTE] "VARIA_REMOTE",
        [FIT_GARMIN_PRODUCT_EDGE25_ASIA] "EDGE25_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE25_JPN] "EDGE25_JPN",
        [FIT_GARMIN_PRODUCT_EDGE20_ASIA] "EDGE20_ASIA",
        [FIT_GARMIN_PRODUCT_APPROACH_X40] "APPROACH_X40",
        [FIT_GARMIN_PRODUCT_FENIX3_JAPAN] "FENIX3_JAPAN",
        [FIT_GARMIN_PRODUCT_VIVO_SMART_EMEA] "VIVO_SMART_EMEA",
        [FIT_GARMIN_PRODUCT_FR630_ASIA] "FR630_ASIA",
        [FIT_GARMIN_PRODUCT_FR630_JPN] "FR630_JPN",
        [FIT_GARMIN_PRODUCT_FR230_JPN] "FR230_JPN",
        [FIT_GARMIN_PRODUCT_HRM4_RUN] "HRM4_RUN",
        [FIT_GARMIN_PRODUCT_EPIX_JAPAN] "EPIX_JAPAN",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE_HR] "VIVO_ACTIVE_HR",
        [FIT_GARMIN_PRODUCT_VIVO_SMART_GPS_HR] "VIVO_SMART_GPS_HR",
        [FIT_GARMIN_PRODUCT_VIVO_SMART_HR] "VIVO_SMART_HR",
        [FIT_GARMIN_PRODUCT_VIVO_SMART_HR_ASIA] "VIVO_SMART_HR_ASIA",
        [FIT_GARMIN_PRODUCT_VIVO_SMART_GPS_HR_ASIA] "VIVO_SMART_GPS_HR_ASIA",
        [FIT_GARMIN_PRODUCT_VIVO_MOVE] "VIVO_MOVE",
        [FIT_GARMIN_PRODUCT_VARIA_TAILLIGHT] "VARIA_TAILLIGHT",
        [FIT_GARMIN_PRODUCT_FR235_ASIA] "FR235_ASIA",
        [FIT_GARMIN_PRODUCT_FR235_JAPAN] "FR235_JAPAN",
        [FIT_GARMIN_PRODUCT_VARIA_VISION] "VARIA_VISION",
        [FIT_GARMIN_PRODUCT_VIVO_FIT3] "VIVO_FIT3",
        [FIT_GARMIN_PRODUCT_FENIX3_KOREA] "FENIX3_KOREA",
        [FIT_GARMIN_PRODUCT_FENIX3_SEA] "FENIX3_SEA",
        [FIT_GARMIN_PRODUCT_FENIX3_HR] "FENIX3_HR",
        [FIT_GARMIN_PRODUCT_VIRB_ULTRA_30] "VIRB_ULTRA_30",
        [FIT_GARMIN_PRODUCT_INDEX_SMART_SCALE] "INDEX_SMART_SCALE",
        [FIT_GARMIN_PRODUCT_FR235] "FR235",
        [FIT_GARMIN_PRODUCT_FENIX3_CHRONOS] "FENIX3_CHRONOS",
        [FIT_GARMIN_PRODUCT_OREGON7XX] "OREGON7XX",
        [FIT_GARMIN_PRODUCT_RINO7XX] "RINO7XX",
        [FIT_GARMIN_PRODUCT_EPIX_KOREA] "EPIX_KOREA",
        [FIT_GARMIN_PRODUCT_FENIX3_HR_CHN] "FENIX3_HR_CHN",
        [FIT_GARMIN_PRODUCT_FENIX3_HR_TWN] "FENIX3_HR_TWN",
        [FIT_GARMIN_PRODUCT_FENIX3_HR_JPN] "FENIX3_HR_JPN",
        [FIT_GARMIN_PRODUCT_FENIX3_HR_SEA] "FENIX3_HR_SEA",
        [FIT_GARMIN_PRODUCT_FENIX3_HR_KOR] "FENIX3_HR_KOR",
        [FIT_GARMIN_PRODUCT_NAUTIX] "NAUTIX",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE_HR_APAC] "VIVO_ACTIVE_HR_APAC",
        [FIT_GARMIN_PRODUCT_FR35] "FR35",
        [FIT_GARMIN_PRODUCT_OREGON7XX_WW] "OREGON7XX_WW",
        [FIT_GARMIN_PRODUCT_EDGE_820] "EDGE_820",
        [FIT_GARMIN_PRODUCT_EDGE_EXPLORE_820] "EDGE_EXPLORE_820",
        [FIT_GARMIN_PRODUCT_FR735XT_APAC] "FR735XT_APAC",
        [FIT_GARMIN_PRODUCT_FR735XT_JAPAN] "FR735XT_JAPAN",
        [FIT_GARMIN_PRODUCT_FENIX5S] "FENIX5S",
        [FIT_GARMIN_PRODUCT_D2_BRAVO_TITANIUM] "D2_BRAVO_TITANIUM",
        [FIT_GARMIN_PRODUCT_VARIA_UT800] "VARIA_UT800",
        [FIT_GARMIN_PRODUCT_RUNNING_DYNAMICS_POD] "RUNNING_DYNAMICS_POD",
        [FIT_GARMIN_PRODUCT_EDGE_820_CHINA] "EDGE_820_CHINA",
        [FIT_GARMIN_PRODUCT_EDGE_820_JAPAN] "EDGE_820_JAPAN",
        [FIT_GARMIN_PRODUCT_FENIX5X] "FENIX5X",
        [FIT_GARMIN_PRODUCT_VIVO_FIT_JR] "VIVO_FIT_JR",
        [FIT_GARMIN_PRODUCT_VIVO_SMART3] "VIVO_SMART3",
        [FIT_GARMIN_PRODUCT_VIVO_SPORT] "VIVO_SPORT",
        [FIT_GARMIN_PRODUCT_EDGE_820_TAIWAN] "EDGE_820_TAIWAN",
        [FIT_GARMIN_PRODUCT_EDGE_820_KOREA] "EDGE_820_KOREA",
        [FIT_GARMIN_PRODUCT_EDGE_820_SEA] "EDGE_820_SEA",
        [FIT_GARMIN_PRODUCT_FR35_HEBREW] "FR35_HEBREW",
        [FIT_GARMIN_PRODUCT_APPROACH_S60] "APPROACH_S60",
        [FIT_GARMIN_PRODUCT_FR35_APAC] "FR35_APAC",
        [FIT_GARMIN_PRODUCT_FR35_JAPAN] "FR35_JAPAN",
        [FIT_GARMIN_PRODUCT_FENIX3_CHRONOS_ASIA] "FENIX3_CHRONOS_ASIA",
        [FIT_GARMIN_PRODUCT_VIRB_360] "VIRB_360",
        [FIT_GARMIN_PRODUCT_FR935] "FR935",
        [FIT_GARMIN_PRODUCT_FENIX5] "FENIX5",
        [FIT_GARMIN_PRODUCT_VIVOACTIVE3] "VIVOACTIVE3",
        [FIT_GARMIN_PRODUCT_FR235_CHINA_NFC] "FR235_CHINA_NFC",
        [FIT_GARMIN_PRODUCT_FORETREX_601_701] "FORETREX_601_701",
        [FIT_GARMIN_PRODUCT_VIVO_MOVE_HR] "VIVO_MOVE_HR",
        [FIT_GARMIN_PRODUCT_EDGE_1030] "EDGE_1030",
        [FIT_GARMIN_PRODUCT_FR35_SEA] "FR35_SEA",
        [FIT_GARMIN_PRODUCT_VECTOR_3] "VECTOR_3",
        [FIT_GARMIN_PRODUCT_FENIX5_ASIA] "FENIX5_ASIA",
        [FIT_GARMIN_PRODUCT_FENIX5S_ASIA] "FENIX5S_ASIA",
        [FIT_GARMIN_PRODUCT_FENIX5X_ASIA] "FENIX5X_ASIA",
        [FIT_GARMIN_PRODUCT_APPROACH_Z80] "APPROACH_Z80",
        [FIT_GARMIN_PRODUCT_FR35_KOREA] "FR35_KOREA",
        [FIT_GARMIN_PRODUCT_D2CHARLIE] "D2CHARLIE",
        [FIT_GARMIN_PRODUCT_VIVO_SMART3_APAC] "VIVO_SMART3_APAC",
        [FIT_GARMIN_PRODUCT_VIVO_SPORT_APAC] "VIVO_SPORT_APAC",
        [FIT_GARMIN_PRODUCT_FR935_ASIA] "FR935_ASIA",
        [FIT_GARMIN_PRODUCT_DESCENT] "DESCENT",
        [FIT_GARMIN_PRODUCT_VIVO_FIT4] "VIVO_FIT4",
        [FIT_GARMIN_PRODUCT_FR645] "FR645",
        [FIT_GARMIN_PRODUCT_FR645M] "FR645M",
        [FIT_GARMIN_PRODUCT_FR30] "FR30",
        [FIT_GARMIN_PRODUCT_FENIX5S_PLUS] "FENIX5S_PLUS",
        [FIT_GARMIN_PRODUCT_EDGE_130] "EDGE_130",
        [FIT_GARMIN_PRODUCT_EDGE_1030_ASIA] "EDGE_1030_ASIA",
        [FIT_GARMIN_PRODUCT_VIVOSMART_4] "VIVOSMART_4",
        [FIT_GARMIN_PRODUCT_VIVO_MOVE_HR_ASIA] "VIVO_MOVE_HR_ASIA",
        [FIT_GARMIN_PRODUCT_APPROACH_X10] "APPROACH_X10",
        [FIT_GARMIN_PRODUCT_FR30_ASIA] "FR30_ASIA",
        [FIT_GARMIN_PRODUCT_VIVOACTIVE3M_W] "VIVOACTIVE3M_W",
        [FIT_GARMIN_PRODUCT_FR645_ASIA] "FR645_ASIA",
        [FIT_GARMIN_PRODUCT_FR645M_ASIA] "FR645M_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE_EXPLORE] "EDGE_EXPLORE",
        [FIT_GARMIN_PRODUCT_GPSMAP66] "GPSMAP66",
        [FIT_GARMIN_PRODUCT_APPROACH_S10] "APPROACH_S10",
        [FIT_GARMIN_PRODUCT_VIVOACTIVE3M_L] "VIVOACTIVE3M_L",
        [FIT_GARMIN_PRODUCT_APPROACH_G80] "APPROACH_G80",
        [FIT_GARMIN_PRODUCT_EDGE_130_ASIA] "EDGE_130_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE_1030_BONTRAGER] "EDGE_1030_BONTRAGER",
        [FIT_GARMIN_PRODUCT_FENIX5_PLUS] "FENIX5_PLUS",
        [FIT_GARMIN_PRODUCT_FENIX5X_PLUS] "FENIX5X_PLUS",
        [FIT_GARMIN_PRODUCT_EDGE_520_PLUS] "EDGE_520_PLUS",
        [FIT_GARMIN_PRODUCT_FR945] "FR945",
        [FIT_GARMIN_PRODUCT_EDGE_530] "EDGE_530",
        [FIT_GARMIN_PRODUCT_EDGE_830] "EDGE_830",
        [FIT_GARMIN_PRODUCT_INSTINCT_ESPORTS] "INSTINCT_ESPORTS",
        [FIT_GARMIN_PRODUCT_FENIX5S_PLUS_APAC] "FENIX5S_PLUS_APAC",
        [FIT_GARMIN_PRODUCT_FENIX5X_PLUS_APAC] "FENIX5X_PLUS_APAC",
        [FIT_GARMIN_PRODUCT_EDGE_520_PLUS_APAC] "EDGE_520_PLUS_APAC",
        [FIT_GARMIN_PRODUCT_FR235L_ASIA] "FR235L_ASIA",
        [FIT_GARMIN_PRODUCT_FR245_ASIA] "FR245_ASIA",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE3M_APAC] "VIVO_ACTIVE3M_APAC",
        [FIT_GARMIN_PRODUCT_GEN3_BSM] "GEN3_BSM",
        [FIT_GARMIN_PRODUCT_GEN3_BCM] "GEN3_BCM",
        [FIT_GARMIN_PRODUCT_VIVO_SMART4_ASIA] "VIVO_SMART4_ASIA",
        [FIT_GARMIN_PRODUCT_VIVOACTIVE4_SMALL] "VIVOACTIVE4_SMALL",
        [FIT_GARMIN_PRODUCT_VIVOACTIVE4_LARGE] "VIVOACTIVE4_LARGE",
        [FIT_GARMIN_PRODUCT_VENU] "VENU",
        [FIT_GARMIN_PRODUCT_MARQ_DRIVER] "MARQ_DRIVER",
        [FIT_GARMIN_PRODUCT_MARQ_AVIATOR] "MARQ_AVIATOR",
        [FIT_GARMIN_PRODUCT_MARQ_CAPTAIN] "MARQ_CAPTAIN",
        [FIT_GARMIN_PRODUCT_MARQ_COMMANDER] "MARQ_COMMANDER",
        [FIT_GARMIN_PRODUCT_MARQ_EXPEDITION] "MARQ_EXPEDITION",
        [FIT_GARMIN_PRODUCT_MARQ_ATHLETE] "MARQ_ATHLETE",
        [FIT_GARMIN_PRODUCT_DESCENT_MK2] "DESCENT_MK2",
        [FIT_GARMIN_PRODUCT_GPSMAP66I] "GPSMAP66I",
        [FIT_GARMIN_PRODUCT_FENIX6S_SPORT] "FENIX6S_SPORT",
        [FIT_GARMIN_PRODUCT_FENIX6S] "FENIX6S",
        [FIT_GARMIN_PRODUCT_FENIX6_SPORT] "FENIX6_SPORT",
        [FIT_GARMIN_PRODUCT_FENIX6] "FENIX6",
        [FIT_GARMIN_PRODUCT_FENIX6X] "FENIX6X",
        [FIT_GARMIN_PRODUCT_HRM_DUAL] "HRM_DUAL",
        [FIT_GARMIN_PRODUCT_HRM_PRO] "HRM_PRO",
        [FIT_GARMIN_PRODUCT_VIVO_MOVE3_PREMIUM] "VIVO_MOVE3_PREMIUM",
        [FIT_GARMIN_PRODUCT_APPROACH_S40] "APPROACH_S40",
        [FIT_GARMIN_PRODUCT_FR245M_ASIA] "FR245M_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE_530_APAC] "EDGE_530_APAC",
        [FIT_GARMIN_PRODUCT_EDGE_830_APAC] "EDGE_830_APAC",
        [FIT_GARMIN_PRODUCT_VIVO_MOVE3] "VIVO_MOVE3",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE4_SMALL_ASIA] "VIVO_ACTIVE4_SMALL_ASIA",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE4_LARGE_ASIA] "VIVO_ACTIVE4_LARGE_ASIA",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE4_OLED_ASIA] "VIVO_ACTIVE4_OLED_ASIA",
        [FIT_GARMIN_PRODUCT_SWIM2] "SWIM2",
        [FIT_GARMIN_PRODUCT_MARQ_DRIVER_ASIA] "MARQ_DRIVER_ASIA",
        [FIT_GARMIN_PRODUCT_MARQ_AVIATOR_ASIA] "MARQ_AVIATOR_ASIA",
        [FIT_GARMIN_PRODUCT_VIVO_MOVE3_ASIA] "VIVO_MOVE3_ASIA",
        [FIT_GARMIN_PRODUCT_FR945_ASIA] "FR945_ASIA",
        [FIT_GARMIN_PRODUCT_VIVO_ACTIVE3T_CHN] "VIVO_ACTIVE3T_CHN",
        [FIT_GARMIN_PRODUCT_MARQ_CAPTAIN_ASIA] "MARQ_CAPTAIN_ASIA",
        [FIT_GARMIN_PRODUCT_MARQ_COMMANDER_ASIA] "MARQ_COMMANDER_ASIA",
        [FIT_GARMIN_PRODUCT_MARQ_EXPEDITION_ASIA] "MARQ_EXPEDITION_ASIA",
        [FIT_GARMIN_PRODUCT_MARQ_ATHLETE_ASIA] "MARQ_ATHLETE_ASIA",
        [FIT_GARMIN_PRODUCT_INSTINCT_SOLAR] "INSTINCT_SOLAR",
        [FIT_GARMIN_PRODUCT_FR45_ASIA] "FR45_ASIA",
        [FIT_GARMIN_PRODUCT_VIVOACTIVE3_DAIMLER] "VIVOACTIVE3_DAIMLER",
        [FIT_GARMIN_PRODUCT_LEGACY_REY] "LEGACY_REY",
        [FIT_GARMIN_PRODUCT_LEGACY_DARTH_VADER] "LEGACY_DARTH_VADER",
        [FIT_GARMIN_PRODUCT_LEGACY_CAPTAIN_MARVEL] "LEGACY_CAPTAIN_MARVEL",
        [FIT_GARMIN_PRODUCT_LEGACY_FIRST_AVENGER] "LEGACY_FIRST_AVENGER",
        [FIT_GARMIN_PRODUCT_FENIX6S_SPORT_ASIA] "FENIX6S_SPORT_ASIA",
        [FIT_GARMIN_PRODUCT_FENIX6S_ASIA] "FENIX6S_ASIA",
        [FIT_GARMIN_PRODUCT_FENIX6_SPORT_ASIA] "FENIX6_SPORT_ASIA",
        [FIT_GARMIN_PRODUCT_FENIX6_ASIA] "FENIX6_ASIA",
        [FIT_GARMIN_PRODUCT_FENIX6X_ASIA] "FENIX6X_ASIA",
        [FIT_GARMIN_PRODUCT_LEGACY_CAPTAIN_MARVEL_ASIA] "LEGACY_CAPTAIN_MARVEL_ASIA",
        [FIT_GARMIN_PRODUCT_LEGACY_FIRST_AVENGER_ASIA] "LEGACY_FIRST_AVENGER_ASIA",
        [FIT_GARMIN_PRODUCT_LEGACY_REY_ASIA] "LEGACY_REY_ASIA",
        [FIT_GARMIN_PRODUCT_LEGACY_DARTH_VADER_ASIA] "LEGACY_DARTH_VADER_ASIA",
        [FIT_GARMIN_PRODUCT_DESCENT_MK2S] "DESCENT_MK2S",
        [FIT_GARMIN_PRODUCT_EDGE_130_PLUS] "EDGE_130_PLUS",
        [FIT_GARMIN_PRODUCT_EDGE_1030_PLUS] "EDGE_1030_PLUS",
        [FIT_GARMIN_PRODUCT_RALLY_200] "RALLY_200",
        [FIT_GARMIN_PRODUCT_FR745] "FR745",
        [FIT_GARMIN_PRODUCT_VENUSQ] "VENUSQ",
        [FIT_GARMIN_PRODUCT_LILY] "LILY",
        [FIT_GARMIN_PRODUCT_MARQ_ADVENTURER] "MARQ_ADVENTURER",
        [FIT_GARMIN_PRODUCT_ENDURO] "ENDURO",
        [FIT_GARMIN_PRODUCT_SWIM2_APAC] "SWIM2_APAC",
        [FIT_GARMIN_PRODUCT_MARQ_ADVENTURER_ASIA] "MARQ_ADVENTURER_ASIA",
        [FIT_GARMIN_PRODUCT_FR945_LTE] "FR945_LTE",
        [FIT_GARMIN_PRODUCT_DESCENT_MK2_ASIA] "DESCENT_MK2_ASIA",
        [FIT_GARMIN_PRODUCT_VENU2] "VENU2",
        [FIT_GARMIN_PRODUCT_VENU2S] "VENU2S",
        [FIT_GARMIN_PRODUCT_VENU_DAIMLER_ASIA] "VENU_DAIMLER_ASIA",
        [FIT_GARMIN_PRODUCT_MARQ_GOLFER] "MARQ_GOLFER",
        [FIT_GARMIN_PRODUCT_VENU_DAIMLER] "VENU_DAIMLER",
        [FIT_GARMIN_PRODUCT_FR745_ASIA] "FR745_ASIA",
        [FIT_GARMIN_PRODUCT_LILY_ASIA] "LILY_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE_1030_PLUS_ASIA] "EDGE_1030_PLUS_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE_130_PLUS_ASIA] "EDGE_130_PLUS_ASIA",
        [FIT_GARMIN_PRODUCT_APPROACH_S12] "APPROACH_S12",
        [FIT_GARMIN_PRODUCT_ENDURO_ASIA] "ENDURO_ASIA",
        [FIT_GARMIN_PRODUCT_VENUSQ_ASIA] "VENUSQ_ASIA",
        [FIT_GARMIN_PRODUCT_EDGE_1040] "EDGE_1040",
        [FIT_GARMIN_PRODUCT_MARQ_GOLFER_ASIA] "MARQ_GOLFER_ASIA",
        [FIT_GARMIN_PRODUCT_VENU2_PLUS] "VENU2_PLUS",
        [FIT_GARMIN_PRODUCT_FR55] "FR55",
        [FIT_GARMIN_PRODUCT_INSTINCT_2] "INSTINCT_2",
        [FIT_GARMIN_PRODUCT_FENIX7S] "FENIX7S",
        [FIT_GARMIN_PRODUCT_FENIX7] "FENIX7",
        [FIT_GARMIN_PRODUCT_FENIX7X] "FENIX7X",
        [FIT_GARMIN_PRODUCT_FENIX7S_APAC] "FENIX7S_APAC",
        [FIT_GARMIN_PRODUCT_FENIX7_APAC] "FENIX7_APAC",
        [FIT_GARMIN_PRODUCT_FENIX7X_APAC] "FENIX7X_APAC",
        [FIT_GARMIN_PRODUCT_APPROACH_G12] "APPROACH_G12",
        [FIT_GARMIN_PRODUCT_DESCENT_MK2S_ASIA] "DESCENT_MK2S_ASIA",
        [FIT_GARMIN_PRODUCT_APPROACH_S42] "APPROACH_S42",
        [FIT_GARMIN_PRODUCT_EPIX_GEN2] "EPIX_GEN2",
        [FIT_GARMIN_PRODUCT_EPIX_GEN2_APAC] "EPIX_GEN2_APAC",
        [FIT_GARMIN_PRODUCT_VENU2S_ASIA] "VENU2S_ASIA",
        [FIT_GARMIN_PRODUCT_VENU2_ASIA] "VENU2_ASIA",
        [FIT_GARMIN_PRODUCT_FR945_LTE_ASIA] "FR945_LTE_ASIA",
        [FIT_GARMIN_PRODUCT_VIVO_MOVE_SPORT] "VIVO_MOVE_SPORT",
        [FIT_GARMIN_PRODUCT_VIVOMOVE_TREND] "VIVOMOVE_TREND",
        [FIT_GARMIN_PRODUCT_APPROACH_S12_ASIA] "APPROACH_S12_ASIA",
        [FIT_GARMIN_PRODUCT_FR255_MUSIC] "FR255_MUSIC",
        [FIT_GARMIN_PRODUCT_FR255_SMALL_MUSIC] "FR255_SMALL_MUSIC",
        [FIT_GARMIN_PRODUCT_FR255] "FR255",
        [FIT_GARMIN_PRODUCT_FR255_SMALL] "FR255_SMALL",
        [FIT_GARMIN_PRODUCT_APPROACH_G12_ASIA] "APPROACH_G12_ASIA",
        [FIT_GARMIN_PRODUCT_APPROACH_S42_ASIA] "APPROACH_S42_ASIA",
        [FIT_GARMIN_PRODUCT_DESCENT_G1] "DESCENT_G1",
        [FIT_GARMIN_PRODUCT_VENU2_PLUS_ASIA] "VENU2_PLUS_ASIA",
        [FIT_GARMIN_PRODUCT_FR955] "FR955",
        [FIT_GARMIN_PRODUCT_FR55_ASIA] "FR55_ASIA",
        [FIT_GARMIN_PRODUCT_VIVOSMART_5] "VIVOSMART_5",
        [FIT_GARMIN_PRODUCT_INSTINCT_2_ASIA] "INSTINCT_2_ASIA",
        [FIT_GARMIN_PRODUCT_MARQ_GEN2] "MARQ_GEN2",
        [FIT_GARMIN_PRODUCT_VENUSQ2] "VENUSQ2",
        [FIT_GARMIN_PRODUCT_VENUSQ2MUSIC] "VENUSQ2MUSIC",
        [FIT_GARMIN_PRODUCT_MARQ_GEN2_AVIATOR] "MARQ_GEN2_AVIATOR",
        [FIT_GARMIN_PRODUCT_D2_AIR_X10] "D2_AIR_X10",
        [FIT_GARMIN_PRODUCT_HRM_PRO_PLUS] "HRM_PRO_PLUS",
        [FIT_GARMIN_PRODUCT_DESCENT_G1_ASIA] "DESCENT_G1_ASIA",
        [FIT_GARMIN_PRODUCT_TACTIX7] "TACTIX7",
        [FIT_GARMIN_PRODUCT_INSTINCT_CROSSOVER] "INSTINCT_CROSSOVER",
        [FIT_GARMIN_PRODUCT_EDGE_EXPLORE2] "EDGE_EXPLORE2",
        [FIT_GARMIN_PRODUCT_TACX_NEO_SMART] "TACX_NEO_SMART",
        [FIT_GARMIN_PRODUCT_TACX_NEO2_SMART] "TACX_NEO2_SMART",
        [FIT_GARMIN_PRODUCT_TACX_NEO2_T_SMART] "TACX_NEO2_T_SMART",
        [FIT_GARMIN_PRODUCT_TACX_NEO_SMART_BIKE] "TACX_NEO_SMART_BIKE",
        [FIT_GARMIN_PRODUCT_TACX_SATORI_SMART] "TACX_SATORI_SMART",
        [FIT_GARMIN_PRODUCT_TACX_FLOW_SMART] "TACX_FLOW_SMART",
        [FIT_GARMIN_PRODUCT_TACX_VORTEX_SMART] "TACX_VORTEX_SMART",
        [FIT_GARMIN_PRODUCT_TACX_BUSHIDO_SMART] "TACX_BUSHIDO_SMART",
        [FIT_GARMIN_PRODUCT_TACX_GENIUS_SMART] "TACX_GENIUS_SMART",
        [FIT_GARMIN_PRODUCT_TACX_FLUX_FLUX_S_SMART] "TACX_FLUX_FLUX_S_SMART",
        [FIT_GARMIN_PRODUCT_TACX_FLUX2_SMART] "TACX_FLUX2_SMART",
        [FIT_GARMIN_PRODUCT_TACX_MAGNUM] "TACX_MAGNUM",
        [FIT_GARMIN_PRODUCT_EDGE_1040_ASIA] "EDGE_1040_ASIA",
        [FIT_GARMIN_PRODUCT_ENDURO2] "ENDURO2",
        [FIT_GARMIN_PRODUCT_SDM4] "SDM4",
        [FIT_GARMIN_PRODUCT_EDGE_REMOTE] "EDGE_REMOTE",
        [FIT_GARMIN_PRODUCT_TACX_TRAINING_APP_WIN] "TACX_TRAINING_APP_WIN",
        [FIT_GARMIN_PRODUCT_TACX_TRAINING_APP_MAC] "TACX_TRAINING_APP_MAC",
        [FIT_GARMIN_PRODUCT_TACX_TRAINING_APP_MAC_CATALYST] "TACX_TRAINING_APP_MAC_CATALYST",
        [FIT_GARMIN_PRODUCT_TRAINING_CENTER] "TRAINING_CENTER",
        [FIT_GARMIN_PRODUCT_TACX_TRAINING_APP_ANDROID] "TACX_TRAINING_APP_ANDROID",
        [FIT_GARMIN_PRODUCT_TACX_TRAINING_APP_IOS] "TACX_TRAINING_APP_IOS",
        [FIT_GARMIN_PRODUCT_TACX_TRAINING_APP_LEGACY] "TACX_TRAINING_APP_LEGACY",
        [FIT_GARMIN_PRODUCT_CONNECTIQ_SIMULATOR] "CONNECTIQ_SIMULATOR",
        [FIT_GARMIN_PRODUCT_ANDROID_ANTPLUS_PLUGIN] "ANDROID_ANTPLUS_PLUGIN",
        [FIT_GARMIN_PRODUCT_CONNECT] "CONNECT",
};

const char *fitGarminProduct(FIT_GARMIN_PRODUCT product)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (product != FIT_GARMIN_PRODUCT_INVALID) {
        str = fitGarminProductTbl[product];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", product);
    }

    return fmtBuf;
}

// Wahoo Fitness products

typedef FIT_UINT16 FIT_WAHOO_FITNESS_PRODUCT;
#define FIT_WAHOO_FITNESS_PRODUCT_INVALID                                        FIT_UINT16_INVALID
#define FIT_WAHOO_FITNESS_TICKR                                                  ((FIT_WAHOO_FITNESS_PRODUCT)7)
#define FIT_WAHOO_FITNESS_ELEMNT_BOLT                                            ((FIT_WAHOO_FITNESS_PRODUCT)31)

static const char *fitWahooFitnessProductTbl[] = {
        [FIT_WAHOO_FITNESS_TICKR] "TICKR",
        [FIT_WAHOO_FITNESS_ELEMNT_BOLT] "ELEMNT_BOLT",
};

const char *fitWahooFitnessProduct(FIT_UINT16 product)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (product != FIT_WAHOO_FITNESS_PRODUCT_INVALID) {
        str = fitWahooFitnessProductTbl[product];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", product);
    }

    return fmtBuf;
}

// Shimano products

typedef FIT_UINT16 FIT_SHIMANO_PRODUCT;
#define FIT_SHIMANO_PRODUCT_INVALID                                              FIT_UINT16_INVALID

static const char *fitShimanoProductTbl[] = {
};

const char *fitShimanoProduct(FIT_UINT16 product)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (product != FIT_SHIMANO_PRODUCT_INVALID) {
        str = fitShimanoProductTbl[product];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", product);
    }

    return fmtBuf;
}

// Favero Electronics products

typedef FIT_UINT16 FIT_FAVERO_ELECTRONICS_PRODUCT;
#define FIT_FAVERO_ELECTRONICS_PRODUCT_INVALID                                   FIT_UINT16_INVALID
#define FIT_FAVERO_ELECTRONICS_ASSIOMA_UNO                                       ((FIT_FAVERO_ELECTRONICS_PRODUCT)10)
#define FIT_FAVERO_ELECTRONICS_ASSIOMA_DUO                                       ((FIT_FAVERO_ELECTRONICS_PRODUCT)12)

static const char *fitFaveroElectronicsProductTbl[] = {
        [FIT_FAVERO_ELECTRONICS_ASSIOMA_UNO] "ASSIOMA_UNO",
        [FIT_FAVERO_ELECTRONICS_ASSIOMA_DUO] "ASSIOMA_DUO",
};

const char *fitFaveroElectronicsProduct(FIT_UINT16 product)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (product != FIT_FAVERO_ELECTRONICS_PRODUCT_INVALID) {
        str = fitFaveroElectronicsProductTbl[product];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", product);
    }

    return fmtBuf;
}

// SRAM products

typedef FIT_UINT16 FIT_SRAM_PRODUCT;
#define FIT_SRAM_PRODUCT_INVALID                                                 FIT_UINT16_INVALID
#define FIT_SRAM_ETAP_AXS                                                        ((FIT_SRAM_PRODUCT)1003)
#define FIT_SRAM_EAGLE_XX1_AXS                                                   ((FIT_SRAM_PRODUCT)1013)

static const char *fitSramProductTbl[] = {
        [FIT_SRAM_ETAP_AXS] "ETAP_AXS",
        [FIT_SRAM_EAGLE_XX1_AXS] "EAGLE_XX1_AXS",
};

const char *fitSramProduct(FIT_UINT16 product)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (product != FIT_SRAM_PRODUCT_INVALID) {
        str = fitSramProductTbl[product];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", product);
    }

    return fmtBuf;
}

const char *fitProduct(FIT_MANUFACTURER manufacturer, FIT_UINT16 product)
{
    static char fmtBuf[32];

    if (manufacturer == FIT_MANUFACTURER_GARMIN) {
        return fitGarminProduct(product);
    } else if (manufacturer == FIT_MANUFACTURER_WAHOO_FITNESS) {
        return fitWahooFitnessProduct(product);
    } else if (manufacturer == FIT_MANUFACTURER_SHIMANO) {
        return fitShimanoProduct(product);
    } else if (manufacturer == FIT_MANUFACTURER_FAVERO_ELECTRONICS) {
        return fitFaveroElectronicsProduct(product);
    } else if (manufacturer == FIT_MANUFACTURER_SRAM) {
        return fitSramProduct(product);
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", product);
    }

    return fmtBuf;
}

static const char *fitAntPlusDeviceTypeTbl[] = {
        [FIT_ANTPLUS_DEVICE_TYPE_ANTFS] "ANTFS",
        [FIT_ANTPLUS_DEVICE_TYPE_BIKE_POWER] "BIKE_POWER",
        [FIT_ANTPLUS_DEVICE_TYPE_ENVIRONMENT_SENSOR_LEGACY] "ENVIRONMENT_SENSOR_LEGACY",
        [FIT_ANTPLUS_DEVICE_TYPE_MULTI_SPORT_SPEED_DISTANCE] "MULTI_SPORT_SPEED_DISTANCE",
        [FIT_ANTPLUS_DEVICE_TYPE_CONTROL] "CONTROL",
        [FIT_ANTPLUS_DEVICE_TYPE_FITNESS_EQUIPMENT] "FITNESS_EQUIPMENT",
        [FIT_ANTPLUS_DEVICE_TYPE_BLOOD_PRESSURE] "BLOOD_PRESSURE",
        [FIT_ANTPLUS_DEVICE_TYPE_GEOCACHE_NODE] "GEOCACHE_NODE",
        [FIT_ANTPLUS_DEVICE_TYPE_LIGHT_ELECTRIC_VEHICLE] "LIGHT_ELECTRIC_VEHICLE",
        [FIT_ANTPLUS_DEVICE_TYPE_ENV_SENSOR] "ENV_SENSOR",
        [FIT_ANTPLUS_DEVICE_TYPE_RACQUET] "RACQUET",
        [FIT_ANTPLUS_DEVICE_TYPE_CONTROL_HUB] "CONTROL_HUB",
        [FIT_ANTPLUS_DEVICE_TYPE_MUSCLE_OXYGEN] "MUSCLE_OXYGEN",
        [FIT_ANTPLUS_DEVICE_TYPE_SHIFTING] "SHIFTING",
        [FIT_ANTPLUS_DEVICE_TYPE_BIKE_LIGHT_MAIN] "BIKE_LIGHT_MAIN",
        [FIT_ANTPLUS_DEVICE_TYPE_BIKE_LIGHT_SHARED] "BIKE_LIGHT_SHARED",
        [FIT_ANTPLUS_DEVICE_TYPE_EXD] "EXD",
        [FIT_ANTPLUS_DEVICE_TYPE_BIKE_RADAR] "BIKE_RADAR",
        [FIT_ANTPLUS_DEVICE_TYPE_BIKE_AERO] "BIKE_AERO",
        [FIT_ANTPLUS_DEVICE_TYPE_WEIGHT_SCALE] "WEIGHT_SCALE",
        [FIT_ANTPLUS_DEVICE_TYPE_HEART_RATE] "HEART_RATE",
        [FIT_ANTPLUS_DEVICE_TYPE_BIKE_SPEED_CADENCE] "BIKE_SPEED_CADENCE",
        [FIT_ANTPLUS_DEVICE_TYPE_BIKE_CADENCE] "BIKE_CADENCE",
        [FIT_ANTPLUS_DEVICE_TYPE_BIKE_SPEED] "BIKE_SPEED",
        [FIT_ANTPLUS_DEVICE_TYPE_STRIDE_SPEED_DISTANCE] "STRIDE_SPEED_DISTANCE",
};

const char *fitAntPlusDeviceType(FIT_ANTPLUS_DEVICE_TYPE type)
{
    const char *str = NULL;
    static char fmtBuf[32];

    if (type != FIT_ANTPLUS_DEVICE_TYPE_INVALID) {
        str = fitAntPlusDeviceTypeTbl[type];
    }

    if (str != NULL) {
        return str;
    } else {
        snprintf(fmtBuf, sizeof (fmtBuf), "%u", type);
    }

    return fmtBuf;
}

static const char *fitBatteryStatusTbl[] = {
        [FIT_BATTERY_STATUS_NEW]        "NEW",
        [FIT_BATTERY_STATUS_GOOD]       "GOOD",
        [FIT_BATTERY_STATUS_OK]         "OK",
        [FIT_BATTERY_STATUS_LOW]        "LOW",
        [FIT_BATTERY_STATUS_CRITICAL]   "CRITICAL",
        [FIT_BATTERY_STATUS_CHARGING]   "CHARGING",
        [FIT_BATTERY_STATUS_UNKNOWN]    "UNKNOWN",
};

const char *fitBatteryStatus(FIT_BATTERY_STATUS status)
{
    if (status != FIT_BATTERY_STATUS_INVALID) {
        return fitBatteryStatusTbl[status];
    }

    return "invalid";
}



